import assert from "node:assert/strict";
import {createHmac} from "node:crypto";
import {notificationReadiness,solapiAuthorization,sendPilotNotification,TEST_NOTIFICATION_TEXT} from "../lib/notification-provider.ts";
const config={SOLAPI_API_KEY:"fixture-key",SOLAPI_API_SECRET:"fixture-secret",SOLAPI_SENDER:"0212345678",NOTIFICATION_PILOT_PHONE:"01000000000",NOTIFICATION_PILOT_USER_ID:"fixture-user",NOTIFICATION_SEND_ENABLED:"true",SOLAPI_KAKAO_PFID:"fixture-pf",SOLAPI_KAKAO_TEMPLATE_ID:"fixture-template"};
assert.equal(notificationReadiness({},"fixture-user","sms").ready,false);
assert.equal(notificationReadiness(config,"other-user","sms").ready,false);
assert.equal(notificationReadiness({...config,NOTIFICATION_SEND_ENABLED:"false"},"fixture-user","sms").ready,false);
assert.equal(notificationReadiness(config,"fixture-user","sms").ready,true);
assert.equal(notificationReadiness({...config,SOLAPI_KAKAO_TEMPLATE_ID:""},"fixture-user","kakao").ready,false);
const date="2026-09-18T00:00:00.000Z",salt="0123456789abcdef0123456789abcdef";
const signature=createHmac("sha256",config.SOLAPI_API_SECRET).update(date+salt).digest("hex");
assert.equal(await solapiAuthorization(config.SOLAPI_API_KEY,config.SOLAPI_API_SECRET,date,salt),`HMAC-SHA256 apiKey=fixture-key, date=${date}, salt=${salt}, signature=${signature}`);
let calls=0;
const accepted=async(url,options)=>{calls++;assert.equal(url,"https://api.solapi.com/messages/v4/send-many/detail");const body=JSON.parse(options.body);assert.equal(body.messages.length,1);assert.equal(body.messages[0].to,config.NOTIFICATION_PILOT_PHONE);assert.equal(body.messages[0].text,TEST_NOTIFICATION_TEXT);return Response.json({messageList:[{messageId:"fixture-message",statusCode:"2000"}],groupInfo:{groupId:"fixture-group",count:{registeredSuccess:1}}});};
assert.equal((await sendPilotNotification(config,"sms","fixture-request",accepted)).status,"accepted");
assert.equal(calls,1);
await sendPilotNotification(config,"kakao","fixture-request",async(_url,options)=>{const body=JSON.parse(options.body);assert.equal(body.messages[0].kakaoOptions.disableSms,true);assert.deepEqual(body.messages[0].kakaoOptions.variables,{});return Response.json({failedMessageList:[{}]});});
assert.equal((await sendPilotNotification(config,"sms","fixture-request",async()=>new Response(null,{status:403}))).status,"failed");
assert.equal((await sendPilotNotification(config,"sms","fixture-request",async()=>new Response(null,{status:503}))).status,"unknown");
let timeoutCalls=0;
assert.equal((await sendPilotNotification(config,"sms","fixture-request",async()=>{timeoutCalls++;throw new Error("timeout");})).status,"unknown");
assert.equal(timeoutCalls,1,"no billable automatic retry");
assert.equal((await sendPilotNotification(config,"sms","fixture-request",async()=>Response.json({}))).status,"unknown");
console.log("Notification mocked checks passed. No network calls or billable messages sent.");
