import assert from "node:assert/strict";
import {interpret,emptyProfile,selectProfileField,resetProfileConditions} from "../lib/profile-model.ts";
import {assess,valueTotals,benefitValueState} from "../lib/benefit-rules.ts";
import {benefits} from "../lib/benefit-catalog.ts";
import {cases} from "./profile-cases.mjs";
let passed=0;let evidencePass=0;const failures=[];
for(const [i,[text,expected]] of cases.entries()){
 const result=interpret(text,2026);
 try{for(const [field,value] of Object.entries(expected))assert.deepEqual(result.patch[field],value,field);passed++;}
 catch(e){failures.push({id:`N${String(i+1).padStart(2,"0")}`,reason:e.message});}
 if(result.evidence.every(e=>text.includes(e.source)))evidencePass++;
}
const kpass=benefits.find(b=>b.id.startsWith("kpass"));
assert.equal(assess(kpass,emptyProfile).status,"check","AC-01 missing profile");
for(const age of [18,19,34,35]){const p={...emptyProfile,age,kpassRegistered:true,transitTrips:20,monthlyTransitCost:60000,confirmedFields:["age","kpassRegistered","transitTrips","monthlyTransitCost"]};assert.equal(assess(kpass,p).status,age>=19&&age<=34?"ready":"watch","AC-02 age boundary");}
assert.equal(assess(kpass,{...emptyProfile,age:27,confirmedFields:["age"]}).estimatedValue,0,"AC-06 incomplete qualification");
const qnet=benefits.find(b=>b.id.startsWith("qnet"));assert.equal(assess(qnet,emptyProfile).estimatedValue,0,"AC-06 no fabricated exam fee");
assert.equal(assess(benefits.find(b=>b.id.startsWith("seoul")),emptyProfile).status,"watch","AC-07 closed intake");
assert.deepEqual(valueTotals([{...kpass,status:"ready",estimatedValue:100},{...qnet,status:"ready",estimatedValue:200}]),{monthly:100,annual:0,one_time:200,non_cash:0},"unit separation");
assert.equal(interpret("부산에 살고 서울로 출근하는 만 30세 직장인이에요.").patch.region,"부산광역시");
assert.equal(interpret("서울에서 직장인으로 일하고 있고 구직자는 아닙니다.").patch.employmentStatus,"employed");
assert.equal(interpret("월 교통비는 6.5만원이에요.").patch.monthlyTransitCost,65000);
const culture=benefits.find(b=>b.id.startsWith("culture"));
assert.equal(assess(culture,emptyProfile,new Date("2026-11-30T19:00:00+09:00")).eligibilityStatus,"needs_info","date-only deadline does not invent 18:00");
assert.equal(assess(culture,emptyProfile,new Date("2026-12-01T00:00:00+09:00")).eligibilityStatus,"closed");
assert.equal(assess(culture,{...emptyProfile,age:3,confirmedFields:["age"]}).eligibilityStatus,"ineligible");
console.log(JSON.stringify({dataset:"50 synthetic examples, not production accuracy",passed,total:cases.length,evidencePass,failures,additionalRegressionChecks:5,ruleChecks:"9 assertions passed"},null,2));
if(passed!==cases.length||evidencePass!==cases.length)process.exitCode=1;
let selected=selectProfileField(emptyProfile,"age",25);
selected=selectProfileField(selected,"region","경기도");
selected=selectProfileField(selected,"employmentStatus","student");
assert.equal(selected.employmentStatus,"student");
assert.deepEqual(selected.confirmedFields,["age","region","employmentStatus"]);
selected=selectProfileField(selected,"annualIncome",0);
assert.ok(selected.confirmedFields.includes("annualIncome"));
selected=selectProfileField(selected,"annualIncome",undefined);
assert.ok(!selected.confirmedFields.includes("annualIncome"));
selected=selectProfileField(selected,"kpassRegistered",false);
assert.ok(selected.confirmedFields.includes("kpassRegistered"));
selected=selectProfileField(selected,"kpassRegistered",undefined);
assert.ok(!selected.confirmedFields.includes("kpassRegistered"));
selected=selectProfileField(selected,"age",undefined);
assert.equal(selected.age,null);
assert.ok(!selected.confirmedFields.includes("age"));
const reset=resetProfileConditions({...selected,consent:true,preferredChannel:"email",name:"검증"});
assert.deepEqual(reset.confirmedFields,[]);
assert.equal(reset.consent,true);
assert.equal(reset.preferredChannel,"email");
assert.equal(emptyProfile.age,null,"original profile is immutable");
console.log("Selection checks passed: explicit values, unknowns, removal, reset and consent preservation.");
assert.equal(benefitValueState(assess(kpass,emptyProfile)),"needs_info");
assert.equal(benefitValueState(assess(qnet,emptyProfile)),"calculation_pending");
assert.equal(benefitValueState({...qnet,status:"watch"}),"excluded");
assert.equal(benefitValueState({...qnet,status:"check",valueCadence:"non_cash"}),"non_cash");
const amountProfile={...emptyProfile,age:27,kpassRegistered:true,transitTrips:20,monthlyTransitCost:60000,confirmedFields:["age","kpassRegistered","transitTrips","monthlyTransitCost"]};
assert.equal(benefitValueState(assess(kpass,amountProfile)),"calculated");
assert.equal(assess(kpass,amountProfile).estimatedValue,18000);
assert.equal(benefitValueState(assess(kpass,{...amountProfile,monthlyTransitCost:0})),"calculated_zero");
assert.equal(benefitValueState(assess(kpass,{...amountProfile,age:35})),"excluded");
console.log("Value-state checks passed: missing inputs, unsupported calculation, non-cash, exclusions, positive amount and explicit zero.");
