// Synthetic evaluation inputs, not interview participants or measured production accuracy.
export const cases = [
 ["서울에 사는 만 27세 직장인이고 혼자 월세로 살아요.",{age:27,region:"서울특별시",employmentStatus:"employed",householdType:"single",housingStatus:"monthly_rent"}],
 ["부산에 사는 만 72세 은퇴자이고 독거예요. 거동이 불편해요.",{age:72,region:"부산광역시",employmentStatus:"retired",householdType:"single",careNeeds:["mobility"]}],
 ["인천의 만 21세 대학생이고 부모님과 같이 살아요.",{age:21,region:"인천광역시",employmentStatus:"student",householdType:"family"}],
 ["대구에 사는 만 38세 전업주부이고 자녀 둘을 키워요.",{age:38,region:"대구광역시",employmentStatus:"homemaker",householdType:"family_with_children"}],
 ["대전에 사는 만 31세 구직자이고 혼자 전세로 살아요.",{age:31,region:"대전광역시",employmentStatus:"job_seeking",housingStatus:"jeonse"}],
 ["울산에 사는 만 45세 자영업자이고 가족과 자가에 살아요.",{age:45,region:"울산광역시",employmentStatus:"self_employed",housingStatus:"owner"}],
 ["세종에 사는 만 29세 회사원이고 혼자 살아요.",{age:29,region:"세종특별자치시",employmentStatus:"employed",householdType:"single"}],
 ["경기도에 사는 만 17세 고등학생이에요.",{age:17,region:"경기도",employmentStatus:"student",householdType:undefined}],
 ["강원특별자치도에 사는 만 68세 은퇴자예요.",{age:68,region:"강원특별자치도",employmentStatus:"retired"}],
 ["충청북도에 사는 만 34세 프리랜서예요.",{age:34,region:"충청북도",employmentStatus:"self_employed"}],
 ["충청남도에 사는 만 22세 대학생이에요.",{age:22,region:"충청남도",employmentStatus:"student"}],
 ["전북특별자치도에 사는 만 49세 구직자예요.",{age:49,region:"전북특별자치도",employmentStatus:"job_seeking"}],
 ["전라남도에 사는 만 76세 독거노인이고 은퇴했어요.",{age:76,region:"전라남도",householdType:"single",employmentStatus:"retired"}],
 ["경상북도에 사는 만 36세 한부모이고 구직 중이에요.",{age:36,region:"경상북도",householdType:"single_parent",employmentStatus:"job_seeking"}],
 ["경상남도에 사는 만 55세 직장인이에요.",{age:55,region:"경상남도",employmentStatus:"employed"}],
 ["제주특별자치도에 사는 만 24세 취준생이에요.",{age:24,region:"제주특별자치도",employmentStatus:"job_seeking"}],
 ["광주광역시에 사는 만 41세 회사원이예요.",{age:41,region:"광주광역시",employmentStatus:"employed"}],
 ["서울 마포구에 사는 만 34세 직장인이에요.",{age:34,region:"서울특별시 마포구",employmentStatus:"employed"}],
 ["부산 해운대구에 사는 만 19세 대학생이에요.",{age:19,region:"부산광역시 해운대구",employmentStatus:"student"}],
 ["저는 1999년생이고 서울에 거주하는 회사원이에요.",{birthYear:1999,age:undefined,region:"서울특별시",employmentStatus:"employed"}],
 ["만 18세이고 서울에 사는 고등학생이에요.",{age:18,region:"서울특별시",employmentStatus:"student"}],
 ["만 19세이고 서울에 사는 구직자예요.",{age:19,employmentStatus:"job_seeking"}],
 ["만 34세이고 서울에 사는 직장인이에요.",{age:34,employmentStatus:"employed"}],
 ["만 35세이고 서울에 사는 직장인이에요.",{age:35,employmentStatus:"employed"}],
 ["만 64세이고 부산에서 은퇴해서 혼자 살아요.",{age:64,region:"부산광역시",householdType:"single",employmentStatus:"retired"}],
 ["만 65세이고 부산에서 은퇴해서 혼자 살아요.",{age:65,region:"부산광역시",householdType:"single",employmentStatus:"retired"}],
 ["저는 34살이고 서울에 사는 직장인이에요.",{age:undefined,birthYear:undefined,region:"서울특별시",employmentStatus:"employed"}],
 ["저는 2099년생이라고 잘못 입력했어요. 나이를 다시 알려드릴게요.",{birthYear:undefined,age:undefined}],
 ["만 132세라고 잘못 썼어요. 현재 나이는 아직 입력하지 않을게요.",{age:undefined}],
 ["서울에서 일하지만 현재 집은 부산이에요. 만 30세 직장인이에요.",{region:"부산광역시",age:30}],
 ["예전에 서울에 살았고 지금은 대전에 살아요. 만 28세예요.",{region:"대전광역시",age:28,employmentStatus:undefined}],
 ["서울이 아니라 인천에 사는 만 23세 대학생이에요.",{region:"인천광역시",age:23}],
 ["서울인지 부산인지 아직 이사할 곳을 정하지 못했어요.",{region:undefined}],
 ["저는 부산에 사는 만 32세 회사원이고 어머니는 만 72세예요.",{age:32,region:"부산광역시",employmentStatus:"employed"}],
 ["만 3세 아이를 키우는 저는 서울에 사는 만 36세 주부예요.",{age:36,region:"서울특별시",employmentStatus:"homemaker",householdType:"family_with_children"}],
 ["저는 대학생이 아니고 지금은 서울에서 회사에 다니고 있어요.",{employmentStatus:"employed"}],
 ["직장을 퇴직한 뒤 지금은 부산에서 구직 중이에요.",{employmentStatus:"job_seeking"}],
 ["서울에서 대학에 재학하면서 회사에도 다녀요.",{employmentStatus:undefined}],
 ["서울에 살고 학자금대출은 없어요.",{hasStudentLoan:false}],
 ["부산 대학생이고 학자금대출이 있어요.",{hasStudentLoan:true,employmentStatus:"student"}],
 ["저는 장애인은 아니고 서울에서 혼자 살아요.",{careNeeds:[],householdType:"single"}],
 ["저는 부산에서 혼자 살고 장애가 있어서 휠체어를 이용해요.",{householdType:"single",careNeeds:["mobility","disability"]}],
 ["자녀는 없고 서울에서 배우자와 둘이 살아요.",{householdType:"couple",careNeeds:[]}],
 ["부산에서 아이 둘을 혼자 키우는 한부모예요.",{householdType:"single_parent",careNeeds:["child_care"]}],
 ["서울에서 할머니와 손자인 제가 함께 사는 조손가구예요.",{householdType:"grandparent_family",age:undefined}],
 ["저는 월세가 아니라 전세로 서울에서 살고 있어요.",{housingStatus:"jeonse"}],
 ["서울 직장인이고 연봉은 3500만원, 월 교통비는 6만원이에요.",{annualIncome:3500,monthlyTransitCost:60000}],
 ["서울 회사원이고 연봉 3,500만원, 월 교통비 6만5천원이에요.",{annualIncome:3500,monthlyTransitCost:65000}],
 ["부산 구직자이고 월 교통비는 65000원, 연 소득은 0원이에요.",{annualIncome:0,monthlyTransitCost:65000,employmentStatus:"job_seeking"}],
 ["서울에 살고 이름은 민서예요. 혜택을 알고 싶어요.",{region:"서울특별시",age:undefined,employmentStatus:undefined,householdType:undefined,annualIncome:undefined}],
];
