"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

type Participant={participant_code:string;status:string;consent_status:string;choices_to_first_benefit:number|null;first_benefit_elapsed_ms:number|null;first_benefit_id:string|null;preparation_started:number;stop_point:string|null;observation:string|null};
type Draft={status:string;consentStatus:string;choicesToFirstBenefit:string;firstBenefitElapsedSeconds:string;firstBenefitId:string;preparationStarted:boolean;stopPoint:string;observation:string};
const codes=["P01","P02","P03","P04","P05"];
const blank:Draft={status:"planned",consentStatus:"pending",choicesToFirstBenefit:"",firstBenefitElapsedSeconds:"",firstBenefitId:"",preparationStarted:false,stopPoint:"",observation:""};
const statusLabel:Record<string,string>={planned:"모집 전",invited:"초대",scheduled:"일정 확정",observed:"관찰 중",completed:"관찰 완료",withdrawn:"철회"};
const fromRow=(row?:Participant):Draft=>row?{status:row.status,consentStatus:row.consent_status,choicesToFirstBenefit:row.choices_to_first_benefit?.toString()??"",firstBenefitElapsedSeconds:row.first_benefit_elapsed_ms?Math.round(row.first_benefit_elapsed_ms/1000).toString():"",firstBenefitId:row.first_benefit_id??"",preparationStarted:Boolean(row.preparation_started),stopPoint:row.stop_point??"",observation:row.observation??""}:{...blank};

export function PilotWorkspace(){
  const [rows,setRows]=useState<Participant[]>([]);const [selected,setSelected]=useState("P01");const [draft,setDraft]=useState<Draft>(blank);const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  const load=useCallback(async(code="P01")=>{const response=await fetch("/api/pilot",{cache:"no-store"});const data=await response.json() as {participants?:Participant[];error?:string};if(!response.ok)throw new Error(data.error);const nextRows=data.participants??[];setRows(nextRows);setDraft(fromRow(nextRows.find(row=>row.participant_code===code)));},[]);
  useEffect(()=>{queueMicrotask(()=>load().catch(error=>setNotice(error.message)));},[load]);
  const metrics=useMemo(()=>({observed:rows.filter(row=>["observed","completed"].includes(row.status)).length,withinThree:rows.filter(row=>row.choices_to_first_benefit!==null&&row.choices_to_first_benefit<=3).length,prepared:rows.filter(row=>Boolean(row.preparation_started)).length}),[rows]);
  async function save(){setBusy(true);setNotice("");try{const response=await fetch("/api/pilot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({participantCode:selected,status:draft.status,consentStatus:draft.consentStatus,choicesToFirstBenefit:draft.choicesToFirstBenefit?Number(draft.choicesToFirstBenefit):null,firstBenefitElapsedSeconds:draft.firstBenefitElapsedSeconds?Number(draft.firstBenefitElapsedSeconds):null,firstBenefitId:draft.firstBenefitId||null,preparationStarted:draft.preparationStarted,stopPoint:draft.stopPoint,observation:draft.observation})});const result=await response.json() as {message?:string;error?:string};if(!response.ok)throw new Error(result.error);await load(selected);setNotice(result.message??"저장했습니다.");}catch(error){setNotice(error instanceof Error?error.message:"저장하지 못했습니다.");}finally{setBusy(false);}}
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge className="bg-[#e2faef] text-[#146047]">익명 5명 탐색 파일럿</Badge><h2 className="mt-3 text-xl font-semibold">서울 청년 5명 파일럿</h2><p className="mt-2 leading-7 text-slate-600">최근 6개월 안에 정책·지원금을 찾아본 서울 거주 만 19~34세 직장인·구직자를 익명 코드로 기록합니다.</p></div><div className="grid grid-cols-3 gap-2 text-center text-sm"><div className="rounded-xl bg-slate-50 p-3"><strong className="block text-lg">{metrics.observed}/5</strong>관찰</div><div className="rounded-xl bg-slate-50 p-3"><strong className="block text-lg">{metrics.withinThree}</strong>3회 내 도달</div><div className="rounded-xl bg-slate-50 p-3"><strong className="block text-lg">{metrics.prepared}</strong>준비 시작</div></div></div>
    <div className="mt-5 flex flex-wrap gap-2">{codes.map(code=>{const row=rows.find(item=>item.participant_code===code);return <Button key={code} variant={selected===code?"default":"outline"} onClick={()=>{setSelected(code);setDraft(fromRow(row));}} aria-pressed={selected===code}>{code} · {statusLabel[row?.status??"planned"]}</Button>;})}</div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><label>진행 상태<NativeSelect className="mt-2" value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value})}>{Object.entries(statusLabel).map(([value,label])=><NativeSelectOption key={value} value={value}>{label}</NativeSelectOption>)}</NativeSelect></label><label>참여 동의<NativeSelect className="mt-2" value={draft.consentStatus} onChange={event=>setDraft({...draft,consentStatus:event.target.value})}><NativeSelectOption value="pending">확인 전</NativeSelectOption><NativeSelectOption value="agreed">동의함</NativeSelectOption><NativeSelectOption value="withdrawn">철회함</NativeSelectOption></NativeSelect></label><label>첫 혜택까지 선택 수<Input className="mt-2" type="number" min={1} max={20} value={draft.choicesToFirstBenefit} onChange={event=>setDraft({...draft,choicesToFirstBenefit:event.target.value})}/></label><label>첫 혜택까지 걸린 시간(초)<Input className="mt-2" type="number" min={1} max={3600} value={draft.firstBenefitElapsedSeconds} onChange={event=>setDraft({...draft,firstBenefitElapsedSeconds:event.target.value})}/></label><label className="sm:col-span-2">처음 확인한 혜택 ID<Input className="mt-2" value={draft.firstBenefitId} onChange={event=>setDraft({...draft,firstBenefitId:event.target.value})} placeholder="예: kpass-youth-2026"/></label><div className="flex items-center gap-3 sm:col-span-2"><Switch id={`prepared-${selected}`} checked={draft.preparationStarted} onCheckedChange={value=>setDraft({...draft,preparationStarted:value})}/><Label htmlFor={`prepared-${selected}`}>서류 확인 또는 신청 준비를 실제로 시작함</Label></div><label className="sm:col-span-2">멈춘 지점<Input className="mt-2" value={draft.stopPoint} onChange={event=>setDraft({...draft,stopPoint:event.target.value})} placeholder="예: 소득 기준을 이해하지 못해 공식 원문에서 멈춤"/></label><label className="sm:col-span-2">관찰 메모<Textarea className="mt-2 min-h-28" value={draft.observation} onChange={event=>setDraft({...draft,observation:event.target.value})} placeholder="말과 행동을 구분해 적고, 실명·연락처·민감서류는 기록하지 않습니다."/></label></div>
    <Button className="mt-5" disabled={busy} onClick={save}>{busy?"저장 중…":`${selected} 관찰 기록 저장`}</Button>{notice&&<p role="status" className="mt-3 text-sm leading-6">{notice}</p>}
  </section>;
}
