"use client";
import {useCallback,useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {benefits} from "@/lib/benefit-catalog";
import {requirements,segments,hypotheses,testTasks,roadmap} from "@/lib/portfolio-framework";
type Row={id:string;kind:string;title:string;body:string;status:string;created_at:string};
type Review={id:string;benefit_id:string;source_url:string;status:string;excerpt:string;previous_excerpt:string;note:string;discovered_at:string;reviewed_at:string};
type Snapshot={records:Row[];reviews:Review[];events:{event_type:string;event_at:string;content_id:string;properties:string}[];cohorts:{cohort:string;started:number;submitted7d:number;mature:number}[];assignments:{experiment_id:string;variant:string;assigned_at:string}[];scope:string;ruleVersion:string};
const panel="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7";
const stamp=(v:string)=>new Date(v).toLocaleString("ko-KR");
export function PortfolioWorkspace(){
 const [data,setData]=useState<Snapshot|null>(null);const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
 const [benefitId,setBenefitId]=useState(benefits[0].id);const [notes,setNotes]=useState<Record<string,string>>({});
 const [kind,setKind]=useState("decision");const [title,setTitle]=useState("");const [body,setBody]=useState("");
 const [hours,setHours]=useState(200);const [fee,setFee]=useState(0);
 const load=useCallback(async()=>{const r=await fetch("/api/portfolio",{cache:"no-store"});const d=await r.json() as Snapshot & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);},[]);
 useEffect(()=>{queueMicrotask(()=>load().catch(e=>setNotice(e.message)));},[load]);
 async function run(payload:object){setBusy(true);setNotice("");try{const r=await fetch("/api/portfolio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json() as {error?:string;message:string};if(!r.ok)throw new Error(d.error);await load();setNotice(d.message);return true;}catch(e){setNotice(e instanceof Error?e.message:"처리하지 못했습니다.");return false;}finally{setBusy(false);}}
 function exportData(){if(!data)return;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),...data},null,2)],{type:"application/json"}));a.download="ahaloop-my-evidence.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 return <div className="mx-auto max-w-6xl space-y-6 px-5 py-8 md:px-9">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-emerald-800">AHALOOP · EVIDENCE LAB</p><h1 className="mt-2 text-3xl font-semibold">운영 검증실</h1><p className="mt-2 text-slate-600">조건부터 결과까지, 판단의 근거를 남깁니다.</p></div><Button variant="outline" disabled={!data} onClick={exportData}>내 근거 기록 내려받기</Button></header>
  <div className="rounded-xl bg-[#0c1b33] p-4 text-sm leading-6 text-slate-100">내 계정의 파일럿 작업공간입니다. 고객 전체 관리자 권한은 제공하지 않습니다. 실제 발송·기관 지급 연동은 미연결이며, 검수 승인도 공개 규칙을 자동 변경하지 않습니다.</div>
  {notice&&<p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4">{notice}</p>}
  <Tabs defaultValue="ba"><TabsList className="flex flex-wrap gap-1 group-data-[orientation=horizontal]/tabs:h-auto [&_[role=tab]]:min-h-11"><TabsTrigger value="ba">요구·판정</TabsTrigger><TabsTrigger value="review">수집·검수</TabsTrigger><TabsTrigger value="crm">CRM 실험</TabsTrigger><TabsTrigger value="research">사용자·결정</TabsTrigger><TabsTrigger value="strategy">사업 판단</TabsTrigger></TabsList>
   <TabsContent value="ba" className="space-y-5 pt-5"><section className={panel}><h2 className="text-xl font-semibold">요구사항과 검증 연결</h2><p className="mt-2 text-sm text-slate-600">현재 규칙 {data?.ruleVersion??"불러오는 중"} · 아래 항목은 수용 기준이며 통과 실적이 아닙니다.</p><div className="mt-5 space-y-3">{requirements.map(([id,title,flow,test])=><div key={id} className="grid gap-1 border-t py-3 sm:grid-cols-[80px_1fr_1fr]"><span className="text-sm font-semibold text-emerald-800">{id}</span><div><strong>{title}</strong><p className="mt-1 text-sm text-slate-600">{flow}</p></div><span className="text-sm">검증: {test}</span></div>)}</div></section><section className={panel}><h2 className="text-xl font-semibold">이전 → 개선 흐름</h2><p className="mt-3 leading-7">키워드 → 데모 기본값 → 혜택 합계 → 상태 덮어쓰기</p><p className="mt-2 font-medium leading-7 text-emerald-800">원문 근거 → 사용자 확인 → 일치·불일치·미확인 → 단위별 계산 → 외부 진행 자기보고 → 단계 이력</p><p className="mt-3 text-sm text-slate-600">현재는 제한된 한국어 규칙 해석입니다. 50개 합성 문장 결과와 실제 사용자 정확도를 구분하며, 소득·재산 등 복잡한 자격 확정은 공식 기관에 확인합니다.</p></section></TabsContent>
   <TabsContent value="review" className="space-y-5 pt-5"><section className={panel}><h2 className="text-xl font-semibold">공식 원문 확인</h2><p className="mt-2 leading-7 text-slate-600">등록한 출처 한 곳을 실제로 조회하고 이전 본문과 비교합니다. 예약 수집이 아닌 수동 실행이며, 본문 변화가 곧 혜택 조건 변화는 아닙니다.</p><div className="mt-4 flex flex-wrap gap-3"><NativeSelect aria-label="수집할 공식 혜택" value={benefitId} onChange={e=>setBenefitId(e.target.value)}>{benefits.map(b=><NativeSelectOption key={b.id} value={b.id}>{b.title}</NativeSelectOption>)}</NativeSelect><Button disabled={busy} onClick={()=>run({action:"collect",benefitId})}>{busy?"처리 중…":"지금 원문 수집"}</Button></div></section>
    {!data?.reviews.length&&<p className={panel}>아직 수집 기록이 없습니다. 실패도 숨기지 않고 기록합니다.</p>}
    {data?.reviews.map(r=><article className={panel} key={r.id}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{benefits.find(b=>b.id===r.benefit_id)?.title}</h3><span className="rounded-lg bg-slate-100 px-3 py-1 text-sm">{({pending:"첫 검수 대기",changed:"변경 감지",unchanged:"변화 없음",failed:"수집 실패",approved:"개인 검수 승인",rejected:"검수 반려"} as Record<string,string>)[r.status]}</span></div><p className="mt-2 text-sm text-slate-600">발견 {stamp(r.discovered_at)}{r.reviewed_at?` · 검수 ${stamp(r.reviewed_at)}`:""}</p><a className="mt-3 inline-block text-emerald-800 underline" href={r.source_url} target="_blank" rel="noreferrer">공식 원문 열기</a><p className="mt-3 text-sm leading-6">{r.note}</p>{r.excerpt&&<details className="mt-4"><summary className="cursor-pointer py-2 font-medium">이전 / 현재 본문 대조</summary><div className="grid gap-4 sm:grid-cols-2"><div><h4>이전 발췌</h4><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-3 font-sans text-sm leading-6">{r.previous_excerpt||"첫 수집"}</pre></div><div><h4>현재 발췌</h4><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-3 font-sans text-sm leading-6">{r.excerpt}</pre></div></div></details>}{["pending","changed"].includes(r.status)&&<div className="mt-4 space-y-3"><label className="block text-sm" htmlFor={`review-${r.id}`}>어떤 조건·기간·금액을 확인했나요? (10자 이상)</label><Textarea id={`review-${r.id}`} value={notes[r.id]??""} onChange={e=>setNotes({...notes,[r.id]:e.target.value})}/><div className="flex gap-3"><Button disabled={busy} onClick={()=>run({action:"review",id:r.id,status:"approved",note:notes[r.id]})}>검수 승인 기록</Button><Button variant="outline" disabled={busy} onClick={()=>run({action:"review",id:r.id,status:"rejected",note:notes[r.id]})}>반려 기록</Button></div></div>}</article>)}</TabsContent>
   <TabsContent value="crm" className="space-y-5 pt-5"><section className={panel}><h2 className="text-xl font-semibold">고객 상태가 다음 메시지를 결정합니다</h2><div className="mt-4 space-y-4">{segments.map(([name,condition,action])=><div key={name} className="border-t pt-3"><strong>{name}</strong><p className="mt-1 text-sm text-slate-600">{condition} → {action}</p></div>)}</div><p className="mt-4 text-sm leading-6 text-slate-600">현재 구현된 발송 전 검사는 동의·중지·조건·미시작·조용한 시간입니다. 중복·발송 피로도 규칙은 실제 발송 연결 전 추가 검증해야 하며, 모든 실제 발송을 차단합니다.</p><div className="mt-4 flex flex-wrap gap-3"><Button disabled={busy} onClick={()=>run({action:"campaign"})}>내 조건으로 발송 전 검사</Button><Button variant="outline" disabled={busy} onClick={()=>run({action:"assign"})}>파일럿 문구 그룹 배정</Button></div>{data?.assignments.map(a=><p key={a.experiment_id} className="mt-3">{a.experiment_id} · {a.variant} 그룹 · {stamp(a.assigned_at)} 배정 (미발송)</p>)}</section>
    <section className={panel}><h2 className="text-xl font-semibold">A/B 문구 실험 계획</h2><p className="mt-3">A: “월 약 ○원 계산 예시, 조건을 확인하세요.”</p><p className="mt-2">B: “신청에 필요한 ○○부터 준비해 보세요.”</p><p className="mt-4 text-sm leading-6 text-slate-600">주지표: 배정 후 7일 내 준비를 시작한 고유 고객 / 적격 배정 고객. 실제 노출이 없으므로 현재 효과는 미측정입니다. 10명 테스트는 이해도 탐색이며 통계적 승자를 선언하지 않습니다.</p></section>
    <section className={panel}><h2 className="text-xl font-semibold">같은 시작 주차의 신청 진행</h2><p className="mt-2 text-sm text-slate-600">신청 건 단위 · UTC 주차 · 감시 제외 · 7일이 지나지 않은 건은 미성숙입니다.</p>{data?.cohorts.length?data.cohorts.map(c=><p className="mt-4" key={c.cohort}>{c.cohort} 시작 {c.started}건 / 7일 내 제출 {c.submitted7d}건 / 7일 관찰 완료 {c.mature}건</p>):<p className="mt-4">아직 신청 시작 기록이 없습니다.</p>}</section>
    <section className={panel}><h2 className="text-xl font-semibold">이벤트 원장</h2><p className="mt-2 text-sm text-slate-600">최근 100건. 미리보기 반응은 preview_*로 분리합니다.</p><div className="mt-4 max-h-80 space-y-3 overflow-auto">{data?.events.map((e,i)=><div key={i} className="border-t pt-3 text-sm"><strong>{e.event_type}</strong><span className="ml-3 text-slate-600">{stamp(e.event_at)}</span>{e.properties&&<p className="mt-1 break-all text-slate-600">{e.properties}</p>}</div>)}</div></section></TabsContent>
   <TabsContent value="research" className="space-y-5 pt-5"><section className={panel}><h2 className="text-xl font-semibold">10명 테스트 준비</h2><p className="mt-3 leading-7">청년 재직·구직 6명, 학생·양육 2명, 중장년·고령 2명을 모집하는 계획입니다. 실제 참여 완료 수가 아닙니다. 본인 사용과 가족 대리 사용을 구분하고, 민감서류는 받지 않습니다.</p><ol className="mt-4 list-inside list-decimal space-y-2">{testTasks.map(t=><li key={t}>{t}</li>)}</ol><p className="mt-4 text-sm leading-6 text-slate-600">40분: 동의 5분 → 최근 실제 경험 10분 → 과제 20분 → 신뢰·부담 5분. 3명 이상 같은 핵심 과제 실패 또는 잘못된 자격 확정·정보 노출은 즉시 중단 기준입니다.</p><a className="mt-3 inline-block text-emerald-800 underline" href="/?test=pilot" target="_blank" rel="noreferrer">내 계정에서 테스트 여정 열기</a><p className="text-sm text-slate-600">현재 비공개 접근 범위는 유지합니다. 외부 참여자 초대는 별도 접근 설정이 필요합니다.</p></section>
    <section className={panel}><h2 className="text-xl font-semibold">관찰 → 근거 → 결정</h2><div className="mt-4 space-y-4"><label className="block">기록 종류<NativeSelect className="mt-2" value={kind} onChange={e=>setKind(e.target.value)}><NativeSelectOption value="decision">제품 결정</NativeSelectOption><NativeSelectOption value="research">사용자 관찰</NativeSelectOption><NativeSelectOption value="experiment">실험 설계·결과</NativeSelectOption></NativeSelect></label><label className="block">제목<Input className="mt-2" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block">근거와 다음 행동<Textarea className="mt-2 min-h-44" value={body} onChange={e=>setBody(e.target.value)} placeholder={kind==="research"?"익명 참가자 ID / 동의 / 과제 / 도움 여부 / 성공 여부 / 시간 / 관찰 발언 / 문제 / 후속 확인일":"문제 / 대안 / 선택과 이유 / 근거 링크·테스트 ID / 위험 / 재검토 조건"}/></label><p className="text-sm text-slate-600">연락처·실명·주민번호·인증키는 기록하지 마세요. 관찰하지 않은 결과는 계획으로 적습니다.</p><Button disabled={busy} onClick={async()=>{if(await run({action:"record",kind,title,body,status:"draft"})){setTitle("");setBody("");}}}>근거 기록 저장</Button></div></section>
    <section className={panel}><h2 className="text-xl font-semibold">사전 가설</h2>{hypotheses.map(([id,h,method])=><div key={id} className="mt-4 border-t pt-3"><strong>{id} · {h}</strong><p className="mt-1 text-sm text-slate-600">{method}</p></div>)}</section></TabsContent>
   <TabsContent value="strategy" className="space-y-5 pt-5"><section className={panel}><h2 className="text-xl font-semibold">권고: 공식 API + 변경 검수부터</h2><p className="mt-3 leading-7">전국·전 생애주기 범위는 유지하되 초기 검증은 소규모로 진행합니다. 경쟁 서비스보다 우월하다는 주장이 아니라, 탐색 이후 조건 확인·신청 준비에서 이탈한다는 가설을 검증합니다.</p><div className="mt-4 space-y-2 text-emerald-800 underline"><p><a target="_blank" rel="noreferrer" href="https://www.data.go.kr/data/15113968/openapi.do">정부 공공서비스 API · 전국 기본망</a></p><p><a target="_blank" rel="noreferrer" href="https://www.data.go.kr/data/15090532/openapi.do">복지로 API · 복지 보완</a></p><p><a target="_blank" rel="noreferrer" href="https://www.youthcenter.go.kr/cmnFooter/openapiIntro/oaiGuide">온통청년 · 인증키 신청</a></p></div><p className="mt-4 text-sm text-slate-600">인증키 미발급. API는 공고 정보이며 개인의 지급 내역이나 자격 확정을 제공하는 것이 아닙니다.</p></section>
    <section className={panel}><h2 className="text-xl font-semibold">비용 민감도 비교</h2><p className="mt-2 text-sm leading-6 text-slate-600">견적이 아닌 계획 가정: 시급 20,000원, 인프라 월 50,000원. 개발비·발송료·세금 제외. 월 1회 건별 검수 기준입니다.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>월 검수 혜택 수<Input type="number" min={0} max={100000} value={hours} onChange={e=>setHours(Math.max(0,Math.min(100000,Number(e.target.value))))}/></label><label>제휴비 가정 (원/월)<Input type="number" min={0} value={fee} onChange={e=>setFee(Math.max(0,Number(e.target.value)))}/></label></div><div className="mt-5 grid gap-4 sm:grid-cols-3">{[["직접 페이지 수집",(20+hours*5/60)*20000+50000,"유지 20시간 + 건당 5분"],["공식 API + 검수",(8+hours*3/60)*20000+50000,"유지 8시간 + 건당 3분"],["제휴",(4+hours*2/60)*20000+50000+fee,"유지 4시간 + 건당 2분 + 제휴비"]].map(([name,cost,basis])=><div className="rounded-xl bg-slate-50 p-4" key={name}><h3>{name}</h3><p className="mt-2 text-xl font-semibold">{Math.round(Number(cost)).toLocaleString()}원</p><p className="mt-2 text-sm text-slate-600">{basis}</p></div>)}</div><p className="mt-4 text-sm">2주 동안 실제 작업시간을 기록한 뒤 가정을 바꿉니다. 무료 검증 후 구독·기관 운영·제휴 광고의 지불의사를 비교합니다.</p></section>
    <section className={panel}><h2 className="text-xl font-semibold">90일 · 날짜보다 검증 결과</h2>{roadmap.map(([day,work])=><p className="mt-4 border-t pt-3" key={day}><strong>{day}</strong> · {work}</p>)}<p className="mt-4 text-sm text-slate-600">주지표는 확인된 수령·이용 완료 사용자 수. 현금 수령액과 비현금 서비스 이용을 분리합니다. 자기보고는 기관 확인과 다릅니다.</p></section></TabsContent>
  </Tabs>
  <section className={panel}><h2 className="text-xl font-semibold">저장된 근거 {data?.records.length??0}건</h2>{data?.records.length?data.records.map(r=><details key={r.id} className="mt-4 border-t pt-3"><summary className="cursor-pointer py-2">{r.title} <span className="text-sm text-slate-500">· {stamp(r.created_at)}</span></summary><pre className="mt-2 whitespace-pre-wrap break-words font-sans text-sm leading-7">{r.body}</pre></details>):<p className="mt-3 text-slate-600">실제 관찰과 결정이 생기면 기록을 추가하세요. 준비만으로 성과를 채우지 않습니다.</p>}</section>
 </div>;
}
