const DAANGN_URL='https://careers.daangn.com/blog/post/%EB%8B%B9%EA%B7%BC-%EC%9D%B8%ED%84%B4-%ED%9A%8C%EC%9D%98%EB%B4%87-%EB%8B%B9%EB%B2%88%EC%9D%B4-%EB%B9%84%EA%B0%9C%EB%B0%9C%EC%9E%90-ai/';
const seedRecords=[
 {id:'daangn-dangbeoni',type:'article',label:'ARTICLE',savedAt:'2026-09-15',sourceDate:'2026.04.30',title:'비개발자로 회의봇 만들기는 처음이라',source:'당근 팀 채용 · Mike (피플팀 GA 인턴)',url:DAANGN_URL,summary:'개발 경험이 없는 피플팀 인턴이 Claude와 대화하며 2주 만에 사내 회의봇 ‘당번이’를 만들고, 운영 오류와 낮은 사용률을 해결해 전사 도구로 성장시킨 기록이에요.',points:['회의 지연, 빈 예약 회의실, 위치 탐색이라는 작은 불편에서 회의 정보·참석 응답·오피스 맵·예약 해제를 한 메시지에 담았어요.','개인 캘린더 노출 사고 뒤 계정별 권한과 토큰을 분리하고 테스트 계정으로 검증하는 안전장치를 마련했어요.','공지보다 실제 회의 안에서 자연스럽게 경험하게 한 방식이 확산에 효과적이었어요. 글에 따르면 251명이 연결했고 하루 평균 약 400건의 알림을 보냈어요.'],quote:'기능을 만드는 것과 사람들이 실제로 쓰게 만드는 것은 완전히 다른 일이었다.',thought:'알림 기능보다 기존 행동 안에서 자연스럽게 경험하게 하는 방법을 먼저 설계해야겠다.',topics:['비개발자 AI','업무 자동화','제품 도입'],confidence:94,uncertainty:'251명과 하루 평균 400건은 회사가 공개한 내부 사례 수치예요.',evidence:[{label:'문제 발견',text:'회의 지연, 사용되지 않는 예약, 회의실 위치 탐색의 불편에서 시작했어요.'},{label:'제작과 운영',text:'Claude와 대화하며 2주 만에 알파 버전을 만들고 권한 분리 문제를 수정했어요.'},{label:'도입 결과',text:'251명이 연결했고 하루 평균 약 400건의 알림이 발송됐다고 글에서 밝혔어요.'}],revisitOn:'2026-10-15',actions:[]},
 {id:'design-memory',type:'video',label:'VIDEO',savedAt:'2026-09-11',sourceDate:'2026.09.11',title:'기억에 남는 순간을 설계하는 제품',source:'YouTube · Design Better',url:'',summary:'기능의 수보다 사용자가 감정을 느끼는 결정적인 순간이 제품의 기억을 만든다는 이야기예요.',points:['첫 성공 경험을 빠르게 제공해요.','작은 문구와 반응이 다음 행동을 만들어요.','사용자가 떠올릴 한 장면을 먼저 설계해요.'],quote:'사람은 기능보다 순간을 기억한다.',thought:'내 생각 한 줄이 기록에 붙는 순간을 강조하자.',topics:['제품 경험','기록 습관'],confidence:78,uncertainty:'영상 전체 자막을 확인하지 않은 시연 분석이에요.',evidence:[{label:'중심 주장',text:'사용자는 모든 기능보다 한두 개의 결정적인 순간을 오래 기억한다고 설명해요.'},{label:'적용 단서',text:'온보딩의 첫 성공과 작은 피드백을 반복해서 강조해요.'}],revisitOn:'2026-09-15',actions:['상세 화면에서 내 생각 입력 순간을 강조하기']},
 {id:'voice-capture',type:'voice',label:'VOICE',savedAt:'2026-09-08',sourceDate:'2026.09.08',title:'저장한 이유를 먼저 묻는 아이디어',source:'음성 메모 · 00:38',url:'',summary:'콘텐츠 요약보다 사용자가 저장한 이유를 빠르게 남기게 하면 기록의 개인적 가치가 커진다는 아이디어예요.',points:['질문은 한 번에 하나만 보여줘요.','음성으로도 답할 수 있게 해요.','답하지 않아도 원본 저장은 끝나요.'],quote:'한 줄의 이유가 요약을 나의 기록으로 바꾼다.',thought:'왜 저장했나요보다 맥락형 질문이 좋겠다.',topics:['기록 습관','음성'],confidence:91,uncertainty:'사용자가 직접 남긴 음성이므로 사실 검증보다 의도 보존에 초점을 맞췄어요.',evidence:[{label:'음성 원문',text:'저장한 이유를 바로 남기게 하면 나중에 다시 봤을 때 더 가치 있지 않을까.'}],revisitOn:'2026-09-22',actions:['저장 직후 질문 문구 3개 비교하기']},
 {id:'image-timeline',type:'image',label:'IMAGE',savedAt:'2026-09-03',sourceDate:'2026.09.03',title:'생각이 이어지는 세로형 타임라인',source:'스크린샷 · 화면 레퍼런스',url:'',summary:'과거 메모와 지금 생각을 같은 흐름에서 비교하는 기록 화면이에요.',points:['날짜보다 생각의 변화가 먼저 보여요.','색을 줄여 내용에 집중해요.','관련 기록이 선으로 연결돼요.'],quote:'기록은 쌓이는 것이 아니라 이어지는 것이다.',thought:'같은 주제를 몇 달 뒤 다시 물어보면 좋겠다.',topics:['제품 경험','재발견'],confidence:72,uncertainty:'이미지만으로 제작 의도까지 확정할 수는 없어요.',evidence:[{label:'화면에서 확인',text:'세로 방향의 날짜와 연결선, 반복되는 메모 카드가 보여요.'}],revisitOn:'2026-10-03',actions:[]},
 {id:'text-question',type:'text',label:'TEXT',savedAt:'2026-09-15',sourceDate:'2026.09.15',title:'좋은 질문은 기록을 행동으로 바꾼다',source:'직접 작성',url:'',summary:'요약 뒤에 나에게 맞는 질문 하나를 덧붙이면 수집한 정보를 다음 생각과 행동으로 이어갈 수 있다는 메모예요.',points:['질문은 하나만 보여줘요.','사용자 역할과 관심사를 반영해요.','답하지 않아도 기록은 보존해요.'],quote:'질문은 기록의 다음 문장이다.',thought:'기획자와 마케터에게 같은 질문을 보여주지 말자.',topics:['기록 습관','제품 경험'],confidence:98,uncertainty:'사용자가 직접 작성한 생각을 구조화한 결과예요.',evidence:[{label:'직접 작성한 원문',text:'좋은 질문은 기록을 행동으로 바꾼다.'}],revisitOn:'2026-09-18',actions:['역할별 질문 템플릿 작성하기']}
];
const STORAGE='memoive-smart-v04-ready';
const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');
const state={records:saved?.records||seedRecords,role:saved?.role||'기획자',resurface:saved?.resurface??true,screen:'home',filter:'all',query:'',captureType:'link',currentId:null,pendingDuplicateId:null,calendarYear:2026,calendarMonth:8,mediaRecorder:null,mediaStream:null,voiceChunks:[],recognition:null};
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const persist=()=>localStorage.setItem(STORAGE,JSON.stringify({records:state.records,role:state.role,resurface:state.resurface}));
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2300)}
function openSheet(id){$('#overlay').classList.add('active');$(id).classList.add('active')}
function closeSheets(){$('#overlay').classList.remove('active');$$('.sheet').forEach(s=>s.classList.remove('active'))}
function go(screen){state.screen=screen;$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===screen));$$('.bottom-nav [data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===screen));if(screen==='home')renderHome();if(screen==='library')renderLibrary();if(screen==='topics')renderTopics();if(screen==='calendar')renderCalendar();window.scrollTo(0,0);if(screen==='library')requestAnimationFrame(()=>{$('#record-search').focus();$('#record-search').scrollIntoView({block:'center'})})}
function normalizeUrl(url=''){try{const u=new URL(url);u.hash='';u.searchParams.sort();return (u.origin+u.pathname+u.search).replace(/\/$/,'').toLowerCase()}catch{return url.trim().replace(/\/$/,'').toLowerCase()}}
function recordQuestion(record){const topic=record.topics[0]||'이 내용';const daangn=record.id.includes('daangn');const map={기획자:daangn?'이 기능이 설명 없이도 자연스럽게 사용되는 첫 순간은 언제여야 할까요?':`${topic}을 제품 흐름에 적용한다면 가장 먼저 바꿀 장면은 무엇일까요?`,마케터:daangn?'공지 대신 실제 사용 장면을 보여준 방식을 MEMOIVE 확산에 어떻게 적용할까요?':`${topic}의 가치를 한 문장으로 전달한다면 어떤 메시지가 좋을까요?`,연구자:daangn?'도입 성과를 더 신뢰하려면 어떤 사용 데이터와 비교 기준이 필요할까요?':`${topic}에 대한 이 주장을 검증하려면 어떤 근거가 더 필요할까요?`,'일상 기록자':daangn?'오늘의 작은 불편 중 직접 바꿔보고 싶은 것은 무엇인가요?':`${topic}이 지금 나의 경험과 연결되는 지점은 무엇인가요?`};return map[state.role]||map.기획자}
function dateLabel(iso){const [y,m,d]=iso.split('-').map(Number);return `${m}월 ${d}일`}
function renderHome(){const due=state.records.filter(r=>r.revisitOn&&r.revisitOn<='2026-09-15').sort((a,b)=>a.revisitOn.localeCompare(b.revisitOn))[0]||state.records[1];$('#resurface-card').classList.toggle('hidden',!state.resurface);$('#resurface-date').textContent=due.revisitOn==='2026-09-15'?'오늘 다시 보기':`${dateLabel(due.savedAt)}의 기록`;$('#resurface-record').dataset.recordId=due.id;$('#resurface-record').innerHTML=`<span class="record-symbol">${esc(due.label)}</span><span><strong>${esc(due.title)}</strong><small>${esc(due.thought||'아직 내 생각이 없어요.')}</small></span><b>→</b>`;$('#home-records').innerHTML=state.records.slice(0,2).map(r=>`<button class="home-card" data-record-id="${r.id}"><span class="home-cover"><span>${esc(r.label)} · ${dateLabel(r.savedAt)}</span><b>${esc(r.topics[0]||'새 기록')}</b></span><strong>${esc(r.title)}</strong><small>${r.thought?'내 생각 있음':'이어 쓰기'}</small></button>`).join('');bindRecordButtons()}
function filteredRecords(){const q=state.query.trim().toLowerCase();return state.records.filter(r=>(state.filter==='all'||r.type===state.filter)&&[r.title,r.source,r.summary,r.thought,...r.topics].join(' ').toLowerCase().includes(q))}
function recordRow(r,cls='record-item'){return `<button class="${cls}" data-record-id="${r.id}"><span class="record-thumb">${esc(r.label)}</span><span><strong>${esc(r.title)}</strong><small>${esc(r.source)} · ${r.thought?'내 생각 있음':'이어 쓰기'}</small></span><b>→</b></button>`}
function renderLibrary(){const list=filteredRecords(),q=state.query.trim();$('#record-list').innerHTML=list.map(r=>recordRow(r)).join('');$('#empty-state').classList.toggle('hidden',list.length>0);$('#search-status').textContent=q?`‘${q}’ 검색 결과 ${list.length}개`:`전체 기록 ${list.length}개`;bindRecordButtons()}
function topicCounts(){const counts={};state.records.forEach(r=>r.topics.forEach(t=>counts[t]=(counts[t]||0)+1));return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))}
function renderTopics(){const entries=topicCounts();$('#topic-grid').innerHTML=entries.map(([name,count])=>`<button class="topic-card" data-topic="${esc(name)}"><span>${String(count).padStart(2,'0')}</span><strong>${esc(name)}</strong><small>${count===entries[0][1]?'가장 자주 기록한 주제':'관련 기록 보기'}</small></button>`).join('');$$('.topic-card').forEach(b=>b.onclick=()=>openTopic(b.dataset.topic))}
function openTopic(topic){const list=state.records.filter(r=>r.topics.includes(topic));$('#topic-title').textContent=topic;$('#topic-description').textContent=`${list.length}개의 기록에서 이 관심사가 반복됐어요.`;$('#topic-record-list').innerHTML=list.map(r=>recordRow(r,'sheet-record')).join('');openSheet('#topic-sheet');bindRecordButtons()}
function monthRecords(){return state.records.filter(r=>{const [y,m]=r.savedAt.split('-').map(Number);return y===state.calendarYear&&m===state.calendarMonth+1})}
function renderCalendar(){const names=['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'];const list=monthRecords();$('#calendar-title').textContent=`${state.calendarYear}년 ${names[state.calendarMonth]}`;$('#calendar-count').textContent=list.length?`${list.length}개의 기록`:'아직 기록이 없어요';const grouped={};list.forEach(r=>{const d=Number(r.savedAt.slice(8,10));(grouped[d]??=[]).push(r)});const first=(new Date(state.calendarYear,state.calendarMonth,1).getDay()+6)%7,days=new Date(state.calendarYear,state.calendarMonth+1,0).getDate();let html='';for(let i=0;i<first;i++)html+='<span></span>';for(let d=1;d<=days;d++){const n=grouped[d]?.length||0,today=state.calendarYear===2026&&state.calendarMonth===8&&d===15;html+=`<button data-day="${d}" class="${n?'has-records':''} ${today?'today':''}"><b>${d}</b>${n>1?`<em>${n}</em>`:''}</button>`}$('#calendar-grid').innerHTML=html;$('#month-record-list').innerHTML=list.length?list.sort((a,b)=>b.savedAt.localeCompare(a.savedAt)).map(r=>`<button class="month-record" data-record-id="${r.id}"><time>${r.savedAt.slice(8,10)}</time><span><strong>${esc(r.title)}</strong><small>${esc(r.source)}</small></span><b>→</b></button>`).join(''):'<div class="empty">이달에 남긴 기록이 없어요.</div>';$$('#calendar-grid button').forEach(b=>b.onclick=()=>openDay(Number(b.dataset.day),grouped[Number(b.dataset.day)]||[]));bindRecordButtons()}
function openDay(day,records){$('#day-title').textContent=`${state.calendarMonth+1}월 ${day}일의 기록`;$('#day-record-list').innerHTML=records.length?records.map(r=>recordRow(r,'sheet-record')).join(''):'<div class="empty">이날은 기록을 쉬었어요.</div>';openSheet('#day-sheet');bindRecordButtons()}
function bindRecordButtons(){$$('[data-record-id]').forEach(b=>b.onclick=()=>{closeSheets();openRecord(b.dataset.recordId)})}
function confidenceLabel(n){return n>=90?`근거 충분 ${n}%`:n>=75?`일부 확인 ${n}%`:`확인 필요 ${n}%`}
function openRecord(id){const r=state.records.find(x=>x.id===id);if(!r)return;state.currentId=id;$('#detail-type').textContent=r.label;$('#detail-confidence').textContent=confidenceLabel(r.confidence);$('#detail-title').textContent=r.title;$('#detail-source').textContent=`${r.source} · ${r.sourceDate}`;$('#detail-tags').innerHTML=r.topics.map(t=>`<span>${esc(t)}</span>`).join('');$('#detail-summary').textContent=r.summary;$('#detail-points').innerHTML=r.points.map(p=>`<li>${esc(p)}</li>`).join('');$('#detail-evidence').innerHTML=r.evidence.map(e=>`<div class="evidence-item"><strong>${esc(e.label)}</strong><small>${esc(e.text)}</small></div>`).join('');$('#evidence-confidence').textContent=confidenceLabel(r.confidence);$('#uncertainty-note').textContent=r.uncertainty;$('#detail-quote').textContent=`“${r.quote}”`;$('#question-role').textContent=state.role;$('#detail-question').textContent=recordQuestion(r);$('#detail-thought').textContent=r.thought||'아직 나만의 기록이 없어요. 한 문장이면 충분해요.';$('#action-section').classList.toggle('hidden',!r.actions?.length);$('#detail-actions').innerHTML=(r.actions||[]).map(a=>`<span>${esc(a)}</span>`).join('');$('#source-link').href=r.url||'#';$('#source-link').style.display=r.url?'flex':'none';$('#revisit-select').value=revisitDays(r.revisitOn);$('#detail-view').classList.add('active');$('#detail-view').scrollTop=0}
function revisitDays(iso){if(!iso)return'0';const a=new Date('2026-09-15T00:00:00'),b=new Date(iso+'T00:00:00'),d=Math.round((b-a)/86400000);return [3,7,30].includes(d)?String(d):'0'}
function openThought(id){const r=state.records.find(x=>x.id===id);if(!r)return;state.currentId=id;$('#thought-question').textContent=recordQuestion(r);$('#thought-input').value=r.thought||'';openSheet('#thought-sheet')}
function saveThought(){const v=$('#thought-input').value.trim();if(!v)return toast('한 문장만 남겨주세요.');const r=state.records.find(x=>x.id===state.currentId);r.thought=v;persist();closeSheets();openRecord(r.id);toast('나만의 기록을 저장했어요.')}
function selectCaptureType(type){state.captureType=type;$$('.capture-types button').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$$('.capture-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===type))}
function daangnCopy(note=''){const r=structuredClone(seedRecords[0]);r.id='daangn-'+Date.now();r.savedAt='2026-09-15';if(note)r.thought=note;return r}
function genericRecord(type,raw,note){const label={link:'ARTICLE',image:'IMAGE',text:'TEXT',voice:'VOICE'}[type],isVoice=type==='voice',isImage=type==='image',source=type==='link'?safeHost(raw):type==='image'?'업로드한 이미지':type==='voice'?'새 음성 메모':'직접 작성한 글';const clean=raw.trim();return{id:'record-'+Date.now(),type:type==='link'?'article':type,label,savedAt:'2026-09-15',sourceDate:'2026.09.15',title:isImage?'이미지에서 발견한 새로운 레퍼런스':isVoice?(clean.slice(0,34)||'새로 남긴 음성 아이디어'):(clean.slice(0,38)||'새로 저장한 콘텐츠'),source,url:type==='link'?raw:'',summary:isImage?'이미지에서 읽은 문자와 시각 정보를 바탕으로 다시 찾기 쉬운 기록으로 정리한 시연 결과예요.':isVoice?'말한 내용을 글로 옮기고 중심 생각과 다음 행동을 구분한 기록이에요.':clean||'공유한 콘텐츠의 중심 내용을 다시 찾기 쉽게 정리한 시연 결과예요.',points:isVoice?['음성 원본을 브라우저에서 녹음했어요.','변환된 문장에서 중심 생각을 찾았어요.','행동을 나타내는 문장을 분리했어요.']:isImage?['선택한 이미지 원본을 확인했어요.','추출된 문자를 사용자가 수정할 수 있어요.','내용을 연결할 주제를 제안했어요.']:['원문을 먼저 보존했어요.','중심 문장과 반복되는 내용을 찾았어요.','내 관심사와 연결할 단서를 제안했어요.'],quote:clean.slice(0,80)||'떠오른 순간을 남기는 것이 기록의 시작이다.',thought:note,topics:isVoice?['음성','아이디어']:isImage?['이미지','레퍼런스']:['새로운 기록'],confidence:type==='text'?96:68,uncertainty:type==='text'?'사용자가 직접 작성한 원문을 구조화했어요.':'실제 AI 서버가 연결되지 않은 시연 분석이므로 원문 확인이 필요해요.',evidence:[{label:isImage?'추출 문자':isVoice?'음성 변환 내용':'입력 원문',text:clean||'자동으로 확인된 문장이 없어 사용자의 검토가 필요해요.'}],revisitOn:'2026-09-22',actions:extractActions(clean)} }
function safeHost(url){try{return new URL(url).hostname.replace('www.','')}catch{return'공유한 링크'}}
function extractActions(text){return text.split(/[.!?\n]/).map(s=>s.trim()).filter(s=>/(해야|하기|만들|확인|작성|적용|보내)/.test(s)).slice(0,3)}
async function submitCapture(event){event.preventDefault();let raw='';if(state.captureType==='link')raw=$('#capture-link').value.trim();if(state.captureType==='text')raw=$('#capture-text').value.trim();if(state.captureType==='image')raw=$('#image-extracted').value.trim();if(state.captureType==='voice')raw=$('#voice-transcript').value.trim();if(!raw&&state.captureType!=='image')return toast('정리할 내용을 입력해 주세요.');if(state.captureType==='link'){const dup=state.records.find(r=>r.url&&normalizeUrl(r.url)===normalizeUrl(raw));if(dup){state.pendingDuplicateId=dup.id;$('#duplicate-card').innerHTML=`<strong>${esc(dup.title)}</strong><small>${esc(dup.source)} · ${dateLabel(dup.savedAt)}에 저장</small>`;closeSheets();setTimeout(()=>openSheet('#duplicate-sheet'),100);return}}const note=$('#capture-note').value.trim();closeSheets();$('#analyzing').classList.add('active');await new Promise(r=>setTimeout(r,1500));const record=state.captureType==='link'&&/careers\.daangn\.com/.test(raw)?daangnCopy(note):genericRecord(state.captureType,raw,note);state.records.unshift(record);persist();$('#analyzing').classList.remove('active');renderAll();openRecord(record.id);toast('근거와 함께 새 기록을 저장했어요.')}
function mergeDuplicate(){const r=state.records.find(x=>x.id===state.pendingDuplicateId),note=$('#duplicate-note').value.trim();if(!note)return toast('이번에 떠오른 생각을 적어주세요.');r.thought=r.thought?`${r.thought}\n${note}`:note;r.savedAt='2026-09-15';persist();closeSheets();renderAll();openRecord(r.id);toast('중복 저장 없이 새 생각만 합쳤어요.')}
function openTopicEdit(){const r=state.records.find(x=>x.id===state.currentId),all=topicCounts().map(([t])=>t);$('#topic-check-list').innerHTML=all.map(t=>`<label><input type="checkbox" value="${esc(t)}" ${r.topics.includes(t)?'checked':''}><span>${esc(t)}</span></label>`).join('');$('#new-topic').value='';openSheet('#topic-edit-sheet')}
function saveRecordTopics(){const r=state.records.find(x=>x.id===state.currentId),picked=$$('#topic-check-list input:checked').map(i=>i.value),newTopic=$('#new-topic').value.trim();if(newTopic&&!picked.includes(newTopic))picked.push(newTopic);if(!picked.length)return toast('주제를 하나 이상 선택해 주세요.');r.topics=picked;persist();closeSheets();renderAll();openRecord(r.id);toast('주제 연결을 저장했어요.')}
function fillTopicSelects(){const topics=topicCounts().map(([t])=>t);['#rename-topic-select','#merge-from','#merge-to'].forEach(id=>$(id).innerHTML=topics.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join(''))}
function renameTopic(){const from=$('#rename-topic-select').value,to=$('#rename-topic-input').value.trim();if(!to)return toast('새 이름을 입력해 주세요.');state.records.forEach(r=>r.topics=r.topics.map(t=>t===from?to:t).filter((t,i,a)=>a.indexOf(t)===i));persist();fillTopicSelects();renderAll();toast(`‘${from}’을 ‘${to}’로 바꿨어요.`)}
function mergeTopics(){const from=$('#merge-from').value,to=$('#merge-to').value;if(from===to)return toast('서로 다른 주제를 선택해 주세요.');state.records.forEach(r=>{if(r.topics.includes(from)){r.topics=r.topics.filter(t=>t!==from);if(!r.topics.includes(to))r.topics.push(to)}});persist();fillTopicSelects();renderAll();toast(`‘${from}’ 기록을 ‘${to}’에 합쳤어요.`)}
async function handleImage(file){if(!file)return;$('#image-file-name').textContent=`${file.name} · 문자 읽는 중…`;$('#image-extracted').value='';if(window.Tesseract){try{const result=await Tesseract.recognize(file,'kor+eng');$('#image-extracted').value=result.data.text.trim();$('#image-file-name').textContent=`${file.name} · 문자 인식 완료`;toast('이미지에서 읽은 문장을 확인해 주세요.');return}catch{}}$('#image-file-name').textContent=`${file.name} · 자동 인식 미지원`;$('#image-extracted').placeholder='이 환경에서는 자동 문자 인식이 어려워요. 중요한 문장을 직접 적어주세요.'}
async function toggleVoice(){const button=$('#voice-button');if(state.mediaRecorder?.state==='recording'){state.mediaRecorder.stop();state.recognition?.stop();button.classList.remove('recording');button.querySelector('strong').textContent='녹음 완료';$('#voice-status').textContent='재생하고 변환된 문장을 확인해 주세요.';return}try{state.mediaStream=await navigator.mediaDevices.getUserMedia({audio:true});state.voiceChunks=[];state.mediaRecorder=new MediaRecorder(state.mediaStream);state.mediaRecorder.ondataavailable=e=>state.voiceChunks.push(e.data);state.mediaRecorder.onstop=()=>{const blob=new Blob(state.voiceChunks,{type:'audio/webm'}),url=URL.createObjectURL(blob),audio=$('#voice-preview');audio.src=url;audio.classList.remove('hidden');state.mediaStream.getTracks().forEach(t=>t.stop())};state.mediaRecorder.start();const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(Recognition){state.recognition=new Recognition();state.recognition.lang='ko-KR';state.recognition.continuous=true;state.recognition.interimResults=true;state.recognition.onresult=e=>{$('#voice-transcript').value=[...e.results].map(r=>r[0].transcript).join(' ')};state.recognition.start()}button.classList.add('recording');button.querySelector('strong').textContent='듣고 있어요… 다시 누르면 완료';$('#voice-status').textContent=Recognition?'말한 내용을 함께 글로 바꾸고 있어요.':'녹음 중이에요. 문자 변환은 직접 확인해 주세요.'}catch{$('#voice-status').textContent='마이크를 사용할 수 없어요. 아래에 내용을 직접 적어도 됩니다.';toast('마이크 권한을 확인해 주세요.')}}
function chooseRole(role){const detailWasOpen=$('#detail-view').classList.contains('active');state.role=role;persist();$('#profile-initial').textContent=role[0];$$('.role-grid button').forEach(b=>b.classList.toggle('active',b.dataset.role===role));toast(`${role} 관점의 질문으로 바꿨어요.`);if(detailWasOpen&&state.currentId)openRecord(state.currentId)}
function renderAll(){renderHome();renderLibrary();renderTopics();renderCalendar();$('#profile-initial').textContent=state.role[0];$$('.role-grid button').forEach(b=>b.classList.toggle('active',b.dataset.role===state.role));$('#resurface-toggle').checked=state.resurface}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#open-search').onclick=()=>{go('library');requestAnimationFrame(()=>$('#record-search').focus())};$('#hero-capture').onclick=$('#nav-capture').onclick=()=>openSheet('#capture-sheet');$('#overlay').onclick=closeSheets;$$('.close-sheet').forEach(b=>b.onclick=closeSheets);$$('.capture-types button').forEach(b=>b.onclick=()=>selectCaptureType(b.dataset.type));$('#capture-form').onsubmit=submitCapture;$('#record-search-form').onsubmit=e=>e.preventDefault();$('#record-search').oninput=e=>{state.query=e.target.value;renderLibrary()};$('#record-search').onkeydown=e=>{if(e.key==='Escape'&&e.target.value){e.preventDefault();e.target.value='';state.query='';renderLibrary()}};$$('.filters button').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;$$('.filters button').forEach(x=>x.classList.toggle('active',x===b));renderLibrary()});$('#prev-month').onclick=()=>{if(--state.calendarMonth<0){state.calendarMonth=11;state.calendarYear--}renderCalendar()};$('#next-month').onclick=()=>{if(++state.calendarMonth>11){state.calendarMonth=0;state.calendarYear++}renderCalendar()};$('#close-detail').onclick=()=>$('#detail-view').classList.remove('active');$('#edit-thought').onclick=()=>openThought(state.currentId);$('#save-thought').onclick=saveThought;$('#merge-duplicate').onclick=mergeDuplicate;$('#open-duplicate').onclick=()=>{const id=state.pendingDuplicateId;closeSheets();openRecord(id)};$('#edit-record-topics').onclick=openTopicEdit;$('#save-record-topics').onclick=saveRecordTopics;$('#manage-topics').onclick=()=>{fillTopicSelects();openSheet('#topic-manage-sheet')};$('#rename-topic').onclick=renameTopic;$('#merge-topics').onclick=mergeTopics;$('#open-profile').onclick=()=>openSheet('#profile-sheet');$$('.role-grid button').forEach(b=>b.onclick=()=>chooseRole(b.dataset.role));$('#resurface-toggle').onchange=e=>{state.resurface=e.target.checked;persist();renderHome();toast(state.resurface?'재발견을 켰어요.':'재발견을 껐어요.')};$('#revisit-select').onchange=e=>{const r=state.records.find(x=>x.id===state.currentId),days=Number(e.target.value);if(!days)r.revisitOn='';else{const d=new Date('2026-09-15T00:00:00');d.setDate(d.getDate()+days);r.revisitOn=d.toISOString().slice(0,10)}persist();renderHome();toast(days?`${e.target.options[e.target.selectedIndex].text} 다시 보여드릴게요.`:'재발견 날짜를 정하지 않았어요.')};$('#capture-image').onchange=e=>handleImage(e.target.files[0]);$('#voice-button').onclick=toggleVoice;$('#share-record').onclick=async()=>{const r=state.records.find(x=>x.id===state.currentId);try{if(navigator.share)await navigator.share({title:r.title,text:r.summary,url:r.url||location.href});else{await navigator.clipboard.writeText(r.url||r.summary);toast('기록을 복사했어요.')}}catch{}};
const params=new URLSearchParams(location.search),sharedUrl=params.get('url'),sharedText=params.get('text'),sharedTitle=params.get('title');if(sharedUrl||sharedText){selectCaptureType(sharedUrl?'link':'text');if(sharedUrl)$('#capture-link').value=sharedUrl;else $('#capture-text').value=[sharedTitle,sharedText].filter(Boolean).join('\n');setTimeout(()=>openSheet('#capture-sheet'),350)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});renderAll();
