'use strict';
const Study = StudyTools, KEY='memoive-self-study-v1', DRAFT=KEY+'-draft';
const el=id=>document.getElementById(id), escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const fields=['scenario','method','device','version','outcome','evidence','friction','next','previousId','change'];
let attempts=[], draft=null, storageError=false;
const status=message=>{el('status').textContent=message;};
const readAttempts=()=>{const saved=localStorage.getItem(KEY);return saved?Study.parseBackup(saved):[];};
const packed=rows=>JSON.stringify({format:'memoive-self-study-v1',exportedAt:new Date().toISOString(),participantCount:rows.length?1:0,attempts:rows},null,2);
el('scenario').innerHTML=Object.entries(Study.scenarios).map(([key,item])=>`<option value="${key}">${item.label}</option>`).join('');
try { attempts=readAttempts(); draft=JSON.parse(localStorage.getItem(DRAFT)||'null'); }
catch { storageError=true; status('저장된 테스트 기록을 읽지 못했어요. 원본은 그대로 두었습니다. 백업을 확인해 주세요.'); }
if(draft && (!draft.id || !Number.isFinite(Date.parse(draft.startedAt)) || !Study.scenarios[draft.scenario])) { draft=null;storageError=true;status('진행 중 기록을 읽지 못했어요. 원본을 덮어쓰지 않았습니다.'); }
function renderPrevious(){const selected=draft?.previousId||el('previousId').value;el('previousId').innerHTML='<option value="">첫 시험 또는 독립적인 시험</option>'+attempts.map(row=>`<option value="${escapeHtml(row.id)}">${escapeHtml(new Date(row.startedAt).toLocaleString('ko-KR'))} · ${escapeHtml(row.version)} · ${escapeHtml(Study.scenarios[row.scenario].label)}</option>`).join('');el('previousId').value=selected;}
renderPrevious();
if(draft) for(const key of fields) if(typeof draft[key]==='string')el(key).value=draft[key];
function updateTask(){const info=Study.scenarios[el('scenario').value];el('task').textContent=info.task;el('criterion').textContent='완료 기준: '+info.criterion;}
function saveDraft(){if(!draft)return true;for(const key of fields)draft[key]=el(key).value;try{localStorage.setItem(DRAFT,JSON.stringify(draft));return true;}catch{status('기기 저장 공간에 기록하지 못했어요. 현재 입력은 화면에 남아 있습니다.');return false;}}
function updateControls(){const running=!!draft&&!draft.endedAt;el('start').disabled=!!draft||storageError;el('stop').disabled=!running;el('assessment').disabled=!draft?.endedAt;for(const key of ['scenario','method','device','version','previousId','change'])el(key).disabled=!!draft;el('timer-label').textContent=running?'측정 중':draft?'측정 종료 · 결과를 남겨주세요':'시작 전';tick();}
function tick(){const seconds=draft?Math.max(0,Math.round(((draft.endedAt?Date.parse(draft.endedAt):Date.now())-Date.parse(draft.startedAt))/1000)):0;el('timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function comparison(row){const previous=attempts.find(item=>item.id===row.previousId);return `<div class="result"><strong>이전의 문제</strong><p>${escapeHtml(previous?.friction||'연결한 이전 기록이 이 기기에 없습니다.')}</p><strong>실제로 바꾼 점</strong><p>${escapeHtml(row.change||'변경 기록 없음')}</p>${previous?`<p>이전: ${escapeHtml(Study.outcomes[previous.outcome])} · ${previous.seconds}초<br>이번: ${escapeHtml(Study.outcomes[row.outcome])} · ${row.seconds}초</p>`:''}<small>과제·자료·기기·도움 여부와 학습효과가 달라질 수 있어요. 시간 차이만으로 효과를 단정하지 않습니다.</small></div>`;}
function render(){el('count').textContent=`${attempts.length}회 · ${attempts.length?1:0}명`;el('summary').innerHTML=Study.summarize(attempts).map(group=>`<div class="result"><strong>${escapeHtml(group.label)}</strong>${group.attempts}회 중 도움 없이 완료 ${group.successes}회<br>완료 시간 중앙값 ${group.median===null?'집계 전':group.median+'초'}</div>`).join('')||'<p>아직 실제 사용 결과가 없어요. 첫 테스트 후 여기에 쌓입니다.</p>';el('history').innerHTML=attempts.map(row=>`<details><summary>${escapeHtml(new Date(row.startedAt).toLocaleString('ko-KR'))} · ${escapeHtml(Study.outcomes[row.outcome])}</summary><p>${escapeHtml(Study.scenarios[row.scenario].label)} / ${escapeHtml(Study.methods[row.method])} / ${row.seconds}초</p><p><strong>완료 근거</strong><br>${escapeHtml(row.evidence)}</p><p><strong>막힌 점</strong><br>${escapeHtml(row.friction)}</p>${row.previousId?comparison(row):''}<p><strong>다음 변경</strong><br>${escapeHtml(row.next||'아직 정하지 않음')}</p><p>${escapeHtml(row.device)} · ${escapeHtml(row.version)}</p></details>`).join('');}
el('scenario').addEventListener('change',updateTask);
el('study-form').addEventListener('input',()=>saveDraft());
el('start').onclick=()=>{if(draft||storageError)return;el('change').required=!!el('previousId').value;if(!el('change').reportValidity())return;if(!el('device').reportValidity()||!el('version').reportValidity())return;draft={id:crypto.randomUUID(),participant:'maker',startedAt:new Date().toISOString(),endedAt:''};if(!saveDraft()){draft=null;return;}status('측정을 시작했어요. 앱에서 과제를 수행한 후 돌아와 종료해 주세요.');updateControls();};
el('stop').onclick=()=>{if(!draft||draft.endedAt)return;draft.endedAt=new Date(Math.max(Date.now(),Date.parse(draft.startedAt))).toISOString();saveDraft();updateControls();el('outcome').focus();};
el('study-form').onsubmit=event=>{event.preventDefault();if(!draft?.endedAt)return;saveDraft();try{const row=Study.validate({...draft,seconds:Math.max(0,(Date.parse(draft.endedAt)-Date.parse(draft.startedAt))/1000)});const merged=Study.merge(readAttempts(),[row]);localStorage.setItem(KEY,packed(merged));attempts=merged;localStorage.removeItem(DRAFT);draft=null;for(const key of ['outcome','evidence','friction','next','previousId','change'])el(key).value='';el('change').required=false;renderPrevious();updateControls();render();status('실제 사용 결과를 이 기기에 저장했어요. 종료 전에 백업 파일도 받아두세요.');}catch(error){status(error.message||'저장하지 못했어요. 입력한 내용은 그대로입니다.');}};
function download(contents,name,type){const url=URL.createObjectURL(new Blob([contents],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
el('export-json').onclick=()=>download(packed(attempts),`memoive-self-study-${Date.now()}.json`,'application/json');
el('export-csv').onclick=()=>download(Study.csv(attempts),`memoive-self-study-${Date.now()}.csv`,'text/csv;charset=utf-8');
el('import-json').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>2*1024*1024)throw new Error('2MB 이하의 테스트 백업을 선택해 주세요.');const imported=Study.parseBackup(await file.text()),merged=Study.merge(readAttempts(),imported);localStorage.setItem(KEY,packed(merged));attempts=merged;renderPrevious();render();status('기존 기록을 덮어쓰지 않고 백업을 합쳤어요.');}catch(error){status(error.message||'백업을 가져오지 못했어요.');}finally{event.target.value='';}};
updateTask();updateControls();render();setInterval(tick,1000);
